Radius/Radius.UI/Models/GitSearchModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Radius.UI.Models
{
    /// <summary>
    /// Cover that holds GET requests data.
    /// </summary>
    [Serializable]
    public class GitSearchModel
    {
        public string toalIssueCountQuery { get; set; }
        public string issuesCountInLast24HrsQuery { get; set; }
        public string issuesCountBtwn24HrsTo7DaysQuery { get; set; }
        public string issuesCountAfter7DaysQuery { get; set; }
    }
}

Radius/Radius.UI/Controllers/StatusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Radius.Core;
using Radius.Core.SearchService;
using Radius.UI.Models;
using Radius.UI.Utils;
using System.IO;
using System.Text;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Radius.UI.Controllers
{
    public class StatusController : Controller
    {
        /// <summary>
        /// Deafult landing page
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// geneates a JSON of queries which Application layer uses to make GET requests
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost]
        [AllowCrossSiteJson]
        public ActionResult GitTableSettings()
        {
            var res = ReadData();
            var settings = new GitSearchSettings(res);
            var model = new GitSearchModel()
            {
                toalIssueCountQuery = settings.ToalIssueCountQuery(),
                issuesCountInLast24HrsQuery = settings.AfterQuery(DateTime.Now.AddDays(-1)),
                issuesCountBtwn24HrsTo7DaysQuery  = settings.BetweenQuery(DateTime.Now.AddDays(-7), DateTime.Now.AddDays(-1)),
                issuesCountAfter7DaysQuery = settings.BeforeQuery(DateTime.Now.AddDays(-7))
            };
            return Json(model);
        }

        /// <summary>
        /// Read the Post data sent from the UI
        /// </summary>
        /// <returns></returns>
        private string ReadData()
        {
            var stream = Request.InputStream;
            stream.Seek(0, SeekOrigin.Begin);
            var readStream = new StreamReader(stream, Encoding.UTF8);
            var json = readStream.ReadToEnd();
            var resp = JsonConvert.DeserializeObject<string>(json);
            return resp;
        }
    }
}

Radius/Radius.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <link rel="icon" href="@Url.Content("~/Images/proj.png")" type="image/png" sizes="64x64">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Radius</title>
    @if (IsSectionDefined("Styles"))
    {@RenderSection("Styles", required: false)}
    <link href="@Url.Content("~/Scripts/plugins/jquery-ui/jquery-ui.css")" rel="stylesheet" type="text/css" />
    @Styles.Render("~/Content/css")
    @Styles.Render("~/font-awesome/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/plugins/slimScroll")

</head>

<body>
    <div class="container body-content m-t-xl">
        @RenderBody()
        <hr/>
        <footer>
            <p>&copy; @DateTime.Now.Year - Radius Git Status</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Radius/Radius.UI/Views/Status/Index.cshtml
<div class="ibox">
    <div class="ibox-title">
        <h5>IMPORTANT</h5>
    </div>
    <div class="ibox-content">
        <div>
            <ul>
                <li>
                    searh text can be any of the following
                    <ul>
                        <li><b>ex: </b>https://github.com/praeclarum/sqlite-net</li>
                        <li><b>ex: </b>https://github.com/praeclarum/sqlite-net.git</li>
                        <li><b>ex: </b>praeclarum/sqlite-net</li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</div>
<div class="ibox">
    <div class="ibox-title">
        <div class="row">
            <div class="col-lg-5">
                <h4>GIT STATUS</h4>
            </div>
            <div class="col-lg-7 text-right">
                <form class="form-inline" role="form" id="searchForm">
                    <input class="form-control w-300" type="text" id="searchTab"/>
                    <button class="btn btn-success">
                        SEARCH
                    </button>
                </form>
            </div>
        </div>
    </div>

    <div class="ibox-content" id="displayArea">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th class="b-r">Duration</th>
                    <th class="text-center">Issue Count</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td class="b-r">Issues opened in last 24 hours</td>
                    <td id="last24" class="text-center">-</td>
                </tr>
                <tr>
                    <td class="b-r">Issues open between last 24 hours to last 7days</td>
                    <td id="last24To7" class="text-center">-</td>
                </tr>
                <tr>
                    <td class="b-r">Issues older than 7 days</td>
                    <td id="beyond7" class="text-center ">-</td>
                </tr>
                <tr>
                    <td class="b-r">Total oppen Issues</td>
                    <td id="total" class="text-center">-</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>


<script>
    function getValue(link, id) {
        $('#' + id).html(spinner());
        $.ajax({
            url: link,
            type: 'GET',
            dataType: 'json',
            success: function (data) {
                if (data.hasOwnProperty('total_count')) {
                    $('#' + id).html(data.total_count);
                } else {
                    $('#' + id).html(0);
                }
            },
            error: function () {
                $('#' + id).html(0);
            }
        });
    }
    $("form#searchForm").submit(function (e) {
        e.preventDefault();
        var searchText = $('#searchTab').val();
        $.ajax({
            url: '@Url.Action("GitTableSettings", "Status")',
            type: 'POST',
            data: JSON.stringify(searchText),
            dataType: 'json',
            success: function (result) {
                getValue(result.toalIssueCountQuery, 'total');
                getValue(result.issuesCountInLast24HrsQuery, 'last24');
                getValue(result.issuesCountBtwn24HrsTo7DaysQuery, 'last24To7');
                getValue(result.issuesCountAfter7DaysQuery, 'beyond7');
            },
            error: function () {
                alert("Internal Error");
            }
        });
    });

    // This is just to help the user understand that search is running
    function spinner(){
        var base = '<div class="sk-spinner sk-spinner-circle">';
        base += '<div class="sk-circle1 sk-circle"></div>';
        base += '<div class="sk-circle2 sk-circle"></div>';
        base += '<div class="sk-circle3 sk-circle"></div>';
        base += '<div class="sk-circle4 sk-circle"></div>';
        base += '<div class="sk-circle5 sk-circle"></div>';
        base += '<div class="sk-circle6 sk-circle"></div>';
        base += '<div class="sk-circle7 sk-circle"></div>';
        base += '<div class="sk-circle8 sk-circle"></div>';
        base += ' <div class="sk-circle9 sk-circle"></div>';
        base += '<div class="sk-circle10 sk-circle"></div>';
        base += ' <div class="sk-circle11 sk-circle"></div>';
        base += '<div class="sk-circle12 sk-circle"></div>';
        base += '</div>';

        return base;
    }
</script>